import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// นำเข้า Noto Sans Thai ฟอนต์
const notoSansThai = localFont({
  src: "../font/Noto_Sans_Thai/NotoSansThai-VariableFont_wdth\,wght.ttf",
  variable: "--font-noto-sans-thai",
  weight: "100 900", // ระบุช่วงน้ำหนักที่ต้องการ
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSansThai.variable} antialiased`} // ใช้ฟอนต์ Noto Sans Thai
      >
        <div className="w-full min-h-screen"></div>
        {children}
      </body>
    </html>
  );
}
